on:
  - push
  - pull_request
name: "Tests"
jobs:
  lint: # TODO: use golanglint-ci
    strategy:
      matrix:
        go-version: [ 1.21, 1.22 ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint
        run: |
          go vet ./...
  unit:
    strategy:
      matrix:
        go-version: [ 1.21, 1.22 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: |
          go test -v -race ./...

    # TODO: check for perf regressions